#!/usr/bin/env bash
# Script that configures Nginx with custom 404 and redirect

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

cat << 'NGINX_CONFIG' | tee /etc/nginx/sites-available/default > /dev/null
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    
    server_name _;
    
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    
    location / {
        try_files $uri $uri/ =404;
    }
}
NGINX_CONFIG

service nginx restart
